# fly.toml app configuration file generated for cosmic-corner on 2023-08-21T15:05:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cosmic-corner"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
